---
extends: default

ignore: |
  gitops/bootstrap/argocd-install/charts/
  gitops/apps/boutique/base/manifests.yaml

rules:
  line-length:
    max: 140
    allow-non-breakable-inline-mappings: true
  document-start: disable
