apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: boutique-aks-devsecops
spec:
  description: Online Boutique application overlays (dev, stage, prod namespaces)
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: boutique-dev
    - server: https://kubernetes.default.svc
      namespace: boutique-stage
    - server: https://kubernetes.default.svc
      namespace: boutique-prod
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
