apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: boutique-aks-devsecops
spec:
  description: Observability stack — Prometheus, Grafana, Alertmanager, OpenTelemetry
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: monitoring
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
